# Name - Parikshit Sahu
## Codsoft Task 4

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error

In [2]:
# Load the movie data (ratings and movie details)
ratings = pd.read_csv(r'C:\Users\sahup\ratings data\ratings.csv')  # Assuming 'ratings.csv' has UserID, MovieID, and Rating columns
movies = pd.read_csv(r'C:\Users\sahup\movies data\movies.csv')    # Assuming 'movies.csv' has MovieID and Title columns

# Display the first few rows of the data
print("Ratings Data:")
ratings = pd.DataFrame(ratings)
ratings.head()

Ratings Data:

   userId  movieId  rating  timestamp
0       1        1     4.0  964982703
1       1        3     4.0  964981247
2       1        6     4.0  964982224
3       1       47     5.0  964983815
4       1       50     5.0  964982931

In [3]:
print("\nMovies Data:")
movies = pd.DataFrame(movies)
movies.head()

Movies Data:

,index,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,...,runtime,spoken_languages,status,tagline,title,vote_average,vote_count,cast,crew,director
0,0,237000000,Action Adventure Fantasy Science Fiction,http://www.avatarmovie.com/,19995,culture clash future space war space colony so...,en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,...,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800,Sam Worthington Zoe Saldana Sigourney Weaver S...,"[{'name': 'Stephen E. Rivkin', 'gender': 0, 'd...",James Cameron
1,1,300000000,Adventure Fantasy Action,http://disney.go.com/disneypictures/pirates/,285,ocean drug abuse exotic island east india trad...,en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,...,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500,Johnny Depp Orlando Bloom Keira Knightley Stel...,"[{'name': 'Dariusz Wolski', 'gender': 2, 'depa...",Gore Verbinski
2,2,245000000,Action Adventure Crime,http://www.sonypictures.com/movies/spectre/,206647,spy based on novel secret agent sequel mi6,en,Spectre,A cryptic message from Bondâ€™s past sends him o...,107.376788,...,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466,Daniel Craig Christoph Waltz L\u00e9a Seydoux ...,"[{'name': 'Thomas Newman', 'gender': 2, 'depar...",Sam Mendes
3,3,250000000,Action Crime Drama Thriller,http://www.thedarkknightrises.com/,49026,dc comics crime fighter terrorist secret ident...,en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,...,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106,Christian Bale Michael Caine Gary Oldman Anne ...,"[{'name': 'Hans Zimmer', 'gender': 2, 'departm...",Christopher Nolan
4,4,260000000,Action Adventure Science Fiction,http://movies.disney.com/john-carter,49529,based on novel mars medallion space travel pri...,en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,...,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124,Taylor Kitsch Lynn Collins Samantha Morton Wil...,"[{'name': 'Andrew Stanton', 'gender': 2, 'depa...",Andrew Stanton

In [4]:
# Remove leading/trailing spaces from column names (if any)
ratings.columns = ratings.columns.str.strip()

# If necessary, rename columns to match expected names
ratings = ratings.rename(columns={
    'userId': 'UserID',    # Adjust 'userId' to 'UserID' if needed
    'movieId': 'MovieID',  # Adjust 'movieId' to 'MovieID' if needed
    'rating': 'Rating'     # Adjust 'rating' to 'Rating' if needed
})
import numpy as np
import pandas as pd
from sklearn.metrics.pairwise import cosine_similarity

# Load the ratings data (ratings.csv)
ratings = pd.read_csv(r'C:\Users\sahup\ratings data\ratings.csv')  # Assuming 'ratings.csv' has UserID, MovieID, and Rating columns
movies = pd.read_csv(r'C:\Users\sahup\movies data\movies.csv')    # Assuming 'movies.csv' has the movie features including 'id' for MovieID

# Check the column names to ensure correct access
print("Column Names in Ratings Data:")
print(ratings.columns)

# Strip leading/trailing spaces from column names
ratings.columns = ratings.columns.str.strip()

# Rename columns if necessary to ensure they are as expected
ratings = ratings.rename(columns={
    'userId': 'UserID',    # Adjust 'userId' to 'UserID' if needed
    'movieId': 'MovieID',  # Adjust 'movieId' to 'MovieID' if needed
    'rating': 'Rating'     # Adjust 'rating' to 'Rating' if needed
})

# Check column names in the movies data
print("\nColumn Names in Movies Data:")
print(movies.columns)

# Strip leading/trailing spaces and rename columns if necessary
movies.columns = movies.columns.str.strip()
movies = movies.rename(columns={'id': 'MovieID'})  # Rename 'id' to 'MovieID'

# Display a sample of the movies data
print("\nSample of Movies Data:")
print(movies.head())

# Create the user-item matrix
user_movie_matrix = ratings.pivot(index='UserID', columns='MovieID', values='Rating')
user_movie_matrix = user_movie_matrix.fillna(0)

# Calculate the cosine similarity between users
user_similarity = cosine_similarity(user_movie_matrix)
user_similarity_df = pd.DataFrame(user_similarity, index=user_movie_matrix.index, columns=user_movie_matrix.index)

# Function to recommend movies to a user
def recommend_movies(user_id, user_movie_matrix, user_similarity_df, num_recommendations=5):
    user_ratings = user_movie_matrix.loc[user_id]  # Get the user's ratings
    
    # Get similarity scores for the user
    similar_users = user_similarity_df[user_id]  
    
    # Compute weighted ratings of all movies based on similar users' ratings
    weighted_ratings = user_movie_matrix.T.dot(similar_users) / np.abs(similar_users).sum()
    
    # Convert the weighted ratings to a Series for easier handling
    weighted_ratings = pd.Series(weighted_ratings, index=user_movie_matrix.columns)
    
    # Recommend the highest-rated movies that the user hasn't rated yet
    recommended_movies = weighted_ratings[~user_ratings.isna()].sort_values(ascending=False).head(num_recommendations)

    # Map MovieID to Movie Titles using the 'title' column in movies data
    recommended_movie_titles = movies[movies['MovieID'].isin(recommended_movies.index)]['title'].values

    return recommended_movie_titles

# Example: Recommend 5 movies for User 1
recommended_movies = recommend_movies(user_id=1, user_movie_matrix=user_movie_matrix, user_similarity_df=user_similarity_df, num_recommendations=5)
print("\nRecommended Movies for User 1:")
print(recommended_movies)

# Verify the changes
print("\nUpdated Column Names in Ratings Data:")
print(ratings.columns)

# Display a sample to ensure it looks correct
print("\nSample of Ratings Data:")
print(ratings.head())

Column Names in Ratings Data:
Index(['userId', 'movieId', 'rating', 'timestamp'], dtype='object')

Column Names in Movies Data:
Index(['index', 'budget', 'genres', 'homepage', 'id', 'keywords',
       'original_language', 'original_title', 'overview', 'popularity',
       'production_companies', 'production_countries', 'release_date',
       'revenue', 'runtime', 'spoken_languages', 'status', 'tagline', 'title',
       'vote_average', 'vote_count', 'cast', 'crew', 'director'],
      dtype='object')

Sample of Movies Data:
   index     budget                                    genres  \
0      0  237000000  Action Adventure Fantasy Science Fiction
1      1  300000000                  Adventure Fantasy Action
2      2  245000000                    Action Adventure Crime
3      3  250000000               Action Crime Drama Thriller
4      4  260000000          Action Adventure Science Fiction

                                       homepage  MovieID  \
0                   http://www.avatarmovie.com/    19995
1  http://disney.go.com/disneypictures/pirates/      285
2   http://www.sonypictures.com/movies/spectre/   206647
3            http://www.thedarkknightrises.com/    49026
4          http://movies.disney.com/john-carter    49529

                                            keywords original_language  \
0  culture clash future space war space colony so...                en
1  ocean drug abuse exotic island east india trad...                en
2         spy based on novel secret agent sequel mi6                en
3  dc comics crime fighter terrorist secret ident...                en
4  based on novel mars medallion space travel pri...                en

                             original_title  \
0                                    Avatar
1  Pirates of the Caribbean: At World's End
2                                   Spectre
3                     The Dark Knight Rises
4                               John Carter

                                            overview  popularity  ... runtime  \
0  In the 22nd century, a paraplegic Marine is di...  150.437577  ...   162.0
1  Captain Barbossa, long believed to be dead, ha...  139.082615  ...   169.0
2  A cryptic message from Bondâ€™s past sends him o...  107.376788  ...   148.0
3  Following the death of District Attorney Harve...  112.312950  ...   165.0
4  John Carter is a war-weary, former military ca...   43.926995  ...   132.0

                                    spoken_languages    status  \
0  [{"iso_639_1": "en", "name": "English"}, {"iso...  Released
1           [{"iso_639_1": "en", "name": "English"}]  Released
2  [{"iso_639_1": "fr", "name": "Fran\u00e7ais"},...  Released
3           [{"iso_639_1": "en", "name": "English"}]  Released
4           [{"iso_639_1": "en", "name": "English"}]  Released

                                          tagline  \
0                     Enter the World of Pandora.
1  At the end of the world, the adventure begins.
2                           A Plan No One Escapes
3                                 The Legend Ends
4            Lost in our world, found in another.

                                      title vote_average vote_count  \
0                                    Avatar          7.2      11800
1  Pirates of the Caribbean: At World's End          6.9       4500
2                                   Spectre          6.3       4466
3                     The Dark Knight Rises          7.6       9106
4                               John Carter          6.1       2124

                                                cast  \
0  Sam Worthington Zoe Saldana Sigourney Weaver S...
1  Johnny Depp Orlando Bloom Keira Knightley Stel...
2  Daniel Craig Christoph Waltz L\u00e9a Seydoux ...
3  Christian Bale Michael Caine Gary Oldman Anne ...
4  Taylor Kitsch Lynn Collins Samantha Morton Wil...

                                                crew           director
0  [{'name': 'Stephen E. Rivkin', 'gender': 0, 'd...      James Cameron
1  [{'name': 'Dariusz Wolski', 'gender': 2, 'depa...     Gore Verbinski
2  [{'name': 'Thomas Newman', 'gender': 2, 'depar...         Sam Mendes
3  [{'name': 'Hans Zimmer', 'gender': 2, 'departm...  Christopher Nolan
4  [{'name': 'Andrew Stanton', 'gender': 2, 'depa...     Andrew Stanton

[5 rows x 24 columns]

Recommended Movies for User 1:
['Terminator 3: Rise of the Machines']

Updated Column Names in Ratings Data:
Index(['UserID', 'MovieID', 'Rating', 'timestamp'], dtype='object')

Sample of Ratings Data:
   UserID  MovieID  Rating  timestamp
0       1        1     4.0  964982703
1       1        3     4.0  964981247
2       1        6     4.0  964982224
3       1       47     5.0  964983815
4       1       50     5.0  964982931